CREATE TABLE "user_role" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(45)
);

CREATE TABLE "user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mall_id" integer,
  "store_id" integer,
  "name" varchar(45),
  "role_id" integer NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "mall" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "city_id" integer NOT NULL,
  "name" varchar(250),
  "tax_id" varchar(45),
  "location" varchar(250)
);

CREATE TABLE "zone" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mall_id" integer NOT NULL,
  "name" varchar(250)
);

CREATE TABLE "store" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "zone_id" integer NOT NULL,
  "name" varchar(250),
  "tax_id" varchar(45),
  "description" text
);

CREATE TABLE "city" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "region_id" integer NOT NULL,
  "name" varchar(250)
);

CREATE TABLE "region" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(250)
);

CREATE TABLE "coupon" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "coupon_type" integer NOT NULL,
  "store_id" integer NOT NULL,
  "description" text,
  "initial_date" date,
  "end_date" date
);

CREATE TABLE "coupon_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(250)
);

CREATE TABLE "validation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" integer NOT NULL,
  "coupon_id" integer NOT NULL,
  "date" date,
  "hour" time
);

CREATE TABLE "client" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "gender_id" integer,
  "dni" varchar(45),
  "first_name" varchar(250),
  "last_name" varchar(250),
  "email" varchar(325),
  "birthday" date
);

CREATE TABLE "gender" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(45)
);

ALTER TABLE "user" ADD CONSTRAINT "rol_user" FOREIGN KEY ("role_id") REFERENCES "user_role" ("id");

ALTER TABLE "city" ADD CONSTRAINT "city_region" FOREIGN KEY ("region_id") REFERENCES "region" ("id");

ALTER TABLE "mall" ADD CONSTRAINT "city_mall" FOREIGN KEY ("city_id") REFERENCES "city" ("id");

ALTER TABLE "zone" ADD CONSTRAINT "mall_zone" FOREIGN KEY ("mall_id") REFERENCES "mall" ("id");

ALTER TABLE "store" ADD CONSTRAINT "zone_store" FOREIGN KEY ("zone_id") REFERENCES "zone" ("id");

ALTER TABLE "user" ADD CONSTRAINT "mall_user" FOREIGN KEY ("mall_id") REFERENCES "mall" ("id");

ALTER TABLE "user" ADD CONSTRAINT "store_user" FOREIGN KEY ("store_id") REFERENCES "store" ("id");

ALTER TABLE "coupon" ADD CONSTRAINT "store_coupon" FOREIGN KEY ("store_id") REFERENCES "store" ("id");

ALTER TABLE "coupon" ADD CONSTRAINT "coupon_type_coupon" FOREIGN KEY ("coupon_type") REFERENCES "coupon_type" ("id");

ALTER TABLE "client" ADD CONSTRAINT "gender_client" FOREIGN KEY ("gender_id") REFERENCES "gender" ("id");

ALTER TABLE "validation" ADD CONSTRAINT "validation_client" FOREIGN KEY ("client_id") REFERENCES "client" ("id");

ALTER TABLE "validation" ADD CONSTRAINT "validation_coupon" FOREIGN KEY ("coupon_id") REFERENCES "coupon" ("id");
